version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - 80:8080
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - laravel-network
  db:
    image: mysql:5.7
    container_name: laravel-db
    restart: always
    environment:
      MYSQL_DATABASE: thai
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    networks:
      - laravel-network
networks:
  laravel-network: