version: '3'
services:
  app:
    build:
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file: .env
    working_dir: /app
    #command: bash -c 'php artisan serve --host 0.0.0.0'
    depends_on:
      - db
    links:
      - db
  db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=thaiticket
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - "3307:3306"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 